version: '3.8'
services:
  app:
    build: .
    container_name: parser_ai
    restart: on-failure
    volumes:
      - .:/app
      - ./sessions:/app/sessions
    env_file: .env
    command: python src/manager.py